### ISSUE TITLE
test result summary missing and  #<DRb::DRbUnknown:0x1017d08a0> in its place

### ISSUE THREAD

**Issue by cswilliams** [sporkrb/spork-testunit#2] opened 2009-12-04 11:06 UTC
I commented about this in your other issue, but didn't realize it was already closed. So, I thought it might be best to open up a new issue for it just in case it's overlooked.  I thought I would also add that I'm using test-unit 2.

I'm experiencing the same weirdness as brian.  For example, running testdrb in my terminal works perfectly:
    >testdrb test/unit/customer_test.rb
    Loaded suite customer_test.rb
    Started
    .....
    Finished in 4.544192 seconds.
    5 tests, 7 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

Yet, if I do the following:
    >testdrb test/unit/customer_test.rb  > output.txt
    > cat output.txt
    Loaded suite customer_test.rb
    Started
    .....
    Finished in 4.537602 seconds.

```
#<DRb::DRbUnknown:0x1017d08a0>
```

You also can get this identical strange output if you just run the testdrb command in textmate from a system() call or equivalent.
I was sort of able to fix it in textmate by wrapping my call to testdrb in a PTY.spawn block, but the output still isn't quite right...

-Chris

**Comment by bjorntrondsen** [comment] 2010-04-23 13:47
I have the same issue with the output in windows' cmd.exe. I haven't been able to find a solution for this. It's a shame, because without spork, test unit is unusable on windows as it takes 20 seconds to load the environment before any tests are run.

**Comment by philomory** [comment] 2010-05-18 20:05
On OS X, using ruby 1.9.1 and rails 3 with Bundler, I don't get any output _at all_, when running my tests; I'm fairly sure they're running, though, since time is spent, etc.

EDIT: (Just a note, I do of course see 'Using TestUnit', 'Loading Spork.prefork block...' and 'Spork is ready and listening on 8988!', in the server terminal. But neither terminal produces any output during test runs.)

**Comment by vitobotta** [comment] 2010-08-07 02:28
Hi... an news on this? I am experiencing the same issue. :(

Finished in 2.113235 seconds.

#DRb::DRbUnknown:0x100348590

**Comment by jpartlow** [comment] 2010-09-08 19:09
I looked into this for a bit.  The test/unit/ui/console/testrunner#test_finished() sends a TestResult to the output, but the local drb client started by testdrb doesn't have a class for this, so you get the DRb::DRbUnknown wrapper.  Adding a require for 'test/unit/testresult' in the testdrb script fixes this for me.  There may be a better solution; I haven't worked with druby myself.

**Comment by teaforthecat** [comment] 2011-02-14 19:23
jpartlow: could you post an example of your fix?

**Comment by jpartlow** [comment] 2011-03-07 01:55
Hi,

Sorry for the late response; I haven't had a chance to dust this off for a while.

So:

Ubuntu 9.10
Ruby 1.8.7
spork 0.8.4
spork-testunit 0.0.4
sqlite3

Setup:

terminal 1:

```
~/dev/$ rails spork-unit-testcase 
~/dev/$ cd spork-unit-testcase
~/dev/spork-unit-testcase$ spork --bootstrap
~/dev/spork-unit-testcase$ vi config/environments/test.rb # add 'config.gem "sqlite3"' to placate the Rail's environment 
~/dev/spork-unit-testcase$ vi test/test_helper.rb # push your config/environment call into the prefork block
~/dev/spork-unit-testcase$ spork
Using TestUnit
Preloading Rails environment
Loading Spork.prefork block...
```

---

terminal 2:

```
~/dev/spork-unit-testcase$ vi test/unit/foo_test.rb # include your test/test_helper.rb and write a minimal testcase
~/dev/spork-unit-testcase$ cat test/unit/foo_test.rb 
require File.expand_path(File.join(File.dirname(__FILE__),'..','test_helper'))

class FooTest

  def test_foo
    assert_equal 1, 2
  end

end
~/dev/spork-unit-testcase$ testdrb test/unit/foo_test.rb 
Loaded suite foo_test.rb
Started
F
Finished in 0.157717 seconds.

  1) Failure:
test_foo(FooTest) [/test/unit/foo_test.rb:6]:
<1> expected but was
<2>.

#<DRb::DRbUnknown:0xb76de7c0>
```

---

sad face

---

terminal 3:

```
~/$ sudo su # DANGER
~/# cd /usr/lib/ruby/gems/1.8/gems/spork-testunit-0.0.4 # NOTE I've manually installed rubygems; apt installs a rubygems that puts gems into /var/lib/gems/1.8, so you may find your spork-testunit-0.0.4 in a different spot.  Mac OSX...er, no clue.  run 'gem environment'
/usr/lib/ruby/gems/1.8/gems/spork-testunit-0.0.4# vi bin/testdrb.rb # add a "require 'test/unit/testresult'"
/usr/lib/ruby/gems/1.8/gems/spork-testunit-0.0.4# cat bin/testdrb.rb
#!/usr/bin/env ruby

require 'test/unit/testresult'
require 'test/unit/failure'
require 'drb'
DRb.start_service("druby://127.0.0.1:0") # this allows Ruby to do some magical stuff so you can pass an output stream over DRb.
test_server = DRbObject.new_with_uri("druby://127.0.0.1:8988")
result = test_server.run(ARGV, $stderr, $stdout)
```

---

terminal 2:

```
~/dev/spork-unit-testcase$ testdrb test/unit/foo_test.rb 
Loaded suite foo_test.rb
Started
F
Finished in 0.012075 seconds.

  1) Failure:
test_foo(FooTest) [/test/unit/foo_test.rb:6]:
<1> expected but was
<2>.

1 tests, 1 assertions, 1 failures, 0 errors
```

---

Rejoicing.

Now, we just edited a library bin as superuser to fix this, so, we probably need to be absolved.

The issue is that druby doesn't know what a Test::Unit::Testresult is, and so outputs it as a DRbUnknown wrapper object.  DRb handles messaging by Marshal.dump and loading arguments to the server instance.  The testdrb wrapper passes the client Ruby space's $stdout.  IO instances cannot be marshaled.  DRb instead wraps a proxy reference around it, and the server makes method requests with marshaled arguments back to this proxy wrapped around the client's $stdout.  But if the client namespace doesn't have a class for something it's been asked to handle, DRb wraps a DRbUnknown instance around it.  In this case our testdrb DRbObject client has no idea what a Test::Unit::TestResult or Failure class is, but it's being given instances of such to display, so we get the DRbUnknown.to_s output instead.  A solution is requiring both the test unit classes in the testdrb script so that they are in the client namespace and $stdout's IO instance can deal with them.  There may be better solutions.

I'll fork this and issue a pull request.  The change is trivial, despite the setup to reproduce and the head scratching.  DRb and Test::Unit are pretty interesting to look at though.

Josh

**Comment by timcharper** [comment] 2011-03-07 17:30
Should be fixed by latest merge on master:

https://github.com/timcharper/spork-testunit/commit/4abdca1eb6e8d01bffa110f288ceddf3cc1a4e21

**Closed as completed by timcharper** 2011-03-07 17:30 UTC
